core/urls.py
from django.conf.urls.defaults import *

import views

urlpatterns = patterns('',
    url(r'^$', views.home, name="home"),
    url(r'^today$', views.today, name="today"),
    url(r'^check$', views.home, name="check"),
    url(r'^rate/(?P<meal_id>.*)/(?P<rating>.*)$', views.rate, name="rate_meal"),
)

urls.py
from django.views.static import serve
from django.conf.urls.defaults import patterns, include, url

from settings import MEDIA_ROOT

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'menus.views.home', name='home'),
    url(r'^', include('Menus.core.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    (r'^media/(?P<path>.*)$', serve,
     {'document_root': MEDIA_ROOT,
      'show_indexes': True}),
)

core/models.py
from django.db import models

# Create your models here.
class MealType(models.Model):
  name = models.TextField()
  time = models.TimeField()

  def __unicode__(self):
    return "%s (%s)" % (self.name, self.time)

class Meal(models.Model):
  type = models.ForeignKey(MealType)
  date = models.DateField()
  notes = models.TextField()

  def __unicode__(self):
    return "%s on %s" % (self.type, self.date)

  def weekday(self):
    return self.date.strftime('%A')

  def rating(self):
    ratings = self.mealrating_set.all()
    rating_sum = sum([rating.rating for rating in ratings])

    if len(ratings) == 0:
      return None
    else:
      return rating_sum / len(ratings)

class MealItem(models.Model):
  meal = models.ForeignKey(Meal)
  name = models.TextField()
  vegetarian = models.BooleanField()
  order = models.IntegerField(default=0)

  def __unicode__(self):
    return "%s for %s" % (self.name, self.meal)

class MealRating(models.Model):
  meal = models.ForeignKey(Meal)
  rating = models.IntegerField(default=0)
  ident = models.TextField()

  def __unicode__(self):
    return "%s %s - %d" % (self.meal.date, self.meal.type.name, self.rating)

core/views.py
import datetime

from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse

from models import Meal, MealType, MealItem, MealRating

def render_with_context(request, *args, **kwargs):
  kwargs['context_instance'] = RequestContext(request)
  
  return render_to_response(*args, **kwargs)

def group_meals(meals):
  groups = []
  group = []
  current_date = None
  for meal in meals:
    if current_date is None or current_date != meal.date:
      if current_date is not None:
        groups.append((current_date.strftime("%A"), current_date, group))
        group = [] 
      current_date = meal.date

    group.append(meal)

  if group != []:
    groups.append((current_date.strftime("%A"), current_date, group))

  return groups

def home(request):
  now = datetime.date.today()
  meals = Meal.objects.filter(date__gte=now).order_by('date', 'type__time')
  #meals = Meal.objects.order_by('date', 'type__time').filter(type__name='Dinner')

  groups = group_meals(meals)

  return render_with_context(request, 'home.html', {'groups': groups,})

def today(request):
  now = datetime.date.today()
  meals = Meal.objects.filter(date=now)
  
  groups = group_meals(meals) 
  
  return render_with_context(request, 'today.html', {'groups': groups,})

def rate(request, meal_id, rating):
  meal = Meal.objects.get(pk=meal_id)
  meal_rating = MealRating.objects.create(meal=meal, rating=rating, ident="")

  return HttpResponseRedirect('/')

core/templates/home.html
{% extends "page.html" %}

{% block header %}
<script>
function toggle_items(meal_id) {
  $('#' + meal_id + ' .meal_item').slideToggle();
  $('#' + meal_id + ' .meal_note').slideToggle();
}
</script>
{% endblock %}

{% block content %}
  {% for weekday, d, meals in groups %}
  <div class='day_title'><span class='weekday'>{{ weekday }}</span> {{ d }}</div>
  <ul class='meals'>
  {% for meal in meals %}
    <li class='meal meal-{{ meal.type.name }}' id='meal-{{ meal.id }}'>
        <ul class='mealitems'>
          <li class='meal_title'><a onclick="toggle_items('meal-{{ meal.id }}')">{{ meal.type.name }}</a></li>
          {% if meal.notes %}<li class='meal_note'>{{ meal.notes }}</li>{% endif %}
          {% for item in meal.mealitem_set.all %}
          <li class='meal_item'>{{ item.name }} {% if item.vegetarian %}(V){% endif %}</li>
          {% endfor %}
        </ul>
        <!--{% if not meal.rating %}
          <a href='{% url rate_meal meal_id=meal.id,rating=1 %}'><img src='/media/stargrey.png'/></a>
          <a href='{% url rate_meal meal_id=meal.id,rating=2 %}'><img src='/media/stargrey.png'/></a>
          <a href='{% url rate_meal meal_id=meal.id,rating=3 %}'><img src='/media/stargrey.png'/></a>
          <a href='{% url rate_meal meal_id=meal.id,rating=4 %}'><img src='/media/stargrey.png'/></a>
          <a href='{% url rate_meal meal_id=meal.id,rating=5 %}'><img src='/media/stargrey.png'/></a>
        {% else %}
          <a href='{% url rate_meal meal_id=meal.id,rating=1 %}'>{% if meal.rating >= 1 %}<img src='/media/star.png'/>{% else %}<img src='/media/unstar.png'/>{% endif %}</a>
          <a href='{% url rate_meal meal_id=meal.id,rating=2 %}'>{% if meal.rating >= 2 %}<img src='/media/star.png'/>{% else %}<img src='/media/unstar.png'/>{% endif %}</a>
          <a href='{% url rate_meal meal_id=meal.id,rating=3 %}'>{% if meal.rating >= 3 %}<img src='/media/star.png'/>{% else %}<img src='/media/unstar.png'/>{% endif %}</a>
          <a href='{% url rate_meal meal_id=meal.id,rating=4 %}'>{% if meal.rating >= 4 %}<img src='/media/star.png'/>{% else %}<img src='/media/unstar.png'/>{% endif %}</a>
          <a href='{% url rate_meal meal_id=meal.id,rating=5 %}'>{% if meal.rating >= 5 %}<img src='/media/star.png'/>{% else %}<img src='/media/unstar.png'/>{% endif %}</a>
        {% endif %}-->
    </li>
  {% endfor %}
  </ul>
  {% empty %}
    <strong>We don't have a menu for this week [yet].</strong>
  {% endfor %}
{% endblock %}

core/templates/today.html
{% extends "page.html" %}

{% block header %}
<link rel="stylesheet" href="/menu/media/embed.css" type="text/css"/>
{% endblock %}

{% block content %}
  {% for weekday, d, meals in groups %}
  <strong>Menu for {{ weekday }} {{ d }}</strong>
  <ul class='meals'>
  {% for meal in meals %}
    <li class='meal'>
        <ul class='mealitems'>
          <li class='meal_title'>{{ meal.type.name }}</li>
          <li class='meal_note'>{{ meal.notes }}</li>
          {% for item in meal.mealitem_set.all %}
          <li class='meal_item'>{{ item.name }} {% if item.vegetarian %}(V){% endif %}</li>
          {% endfor %}
        </ul>
        <!--{% if not meal.rating %}
          <a href='{% url rate_meal meal_id=meal.id,rating=1 %}'><img src='/media/stargrey.png'/></a>
          <a href='{% url rate_meal meal_id=meal.id,rating=2 %}'><img src='/media/stargrey.png'/></a>
          <a href='{% url rate_meal meal_id=meal.id,rating=3 %}'><img src='/media/stargrey.png'/></a>
          <a href='{% url rate_meal meal_id=meal.id,rating=4 %}'><img src='/media/stargrey.png'/></a>
          <a href='{% url rate_meal meal_id=meal.id,rating=5 %}'><img src='/media/stargrey.png'/></a>
        {% else %}
          <a href='{% url rate_meal meal_id=meal.id,rating=1 %}'>{% if meal.rating >= 1 %}<img src='/media/star.png'/>{% else %}<img src='/media/unstar.png'/>{% endif %}</a>
          <a href='{% url rate_meal meal_id=meal.id,rating=2 %}'>{% if meal.rating >= 2 %}<img src='/media/star.png'/>{% else %}<img src='/media/unstar.png'/>{% endif %}</a>
          <a href='{% url rate_meal meal_id=meal.id,rating=3 %}'>{% if meal.rating >= 3 %}<img src='/media/star.png'/>{% else %}<img src='/media/unstar.png'/>{% endif %}</a>
          <a href='{% url rate_meal meal_id=meal.id,rating=4 %}'>{% if meal.rating >= 4 %}<img src='/media/star.png'/>{% else %}<img src='/media/unstar.png'/>{% endif %}</a>
          <a href='{% url rate_meal meal_id=meal.id,rating=5 %}'>{% if meal.rating >= 5 %}<img src='/media/star.png'/>{% else %}<img src='/media/unstar.png'/>{% endif %}</a>
        {% endif %}-->
    </li>
  {% endfor %}
  </ul>
  {% endfor %}
{% endblock %}

templates/page.html
<html>
<head>
<meta name="viewport" content="width=320" />
<link rel="stylesheet" href="/menu/media/grid.css" type="text/css"/>
<link rel="stylesheet" href="/menu/media/screen.css" type="text/css"/>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
{% block header %}

{% endblock %}
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '{{ ga_account }}']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
<div class='container_12'>
{% block content %}
{% endblock %}
</div>
</body>
</html>